---
title: "Exam_2_niedzwiecki"
format: pdf
editor: visual
---

```{r}
#install and read packages

library(tidyverse)
library(knitr)
library(ggplot2)
library(dplyr)
library(lubridate)
#read in data

rivers <- read_csv('rivers.csv')
wqs <- read_csv('wqs.csv')

#spelling
rivers <- rivers %>%
 mutate( 
    site = case_when(
      site %in% c("Galatin", "Gallatiin", "Gallatin") ~ "Gallatin",
      site %in% c("Madison", "Madison River") ~ "Madison",
      site %in% c("Misouri", "Missouri") ~ "Missouri",
      TRUE ~ site
    ))

#create a df with rivers as variables

rivers_avg <- rivers %>%
   mutate(site = case_when(
    site %in% c("Galatin", "Gallatiin", "Gallatin") ~ "Gallatin",
    site %in% c("Madison", "Madison River") ~ "Madison",
    site %in% c("Misouri", "Missouri") ~ "Missouri",
    TRUE ~ site
  ))%>%
  
  group_by(site) %>%
  summarise(
    avg_temp = mean(temperature, na.rm = TRUE),
    avg_o2   = mean(dissolved_oxygen, na.rm = TRUE),
    avg_ph   = mean(pH, na.rm = TRUE),
    .groups = "drop"
  )

# Display table 

rivers_avg_present <- rivers_avg %>%
  rename(
    "Watershed"        = site,
    "Temperture (C)"= avg_temp,
    "Dissolved O2 (mg/L)"= avg_o2,
    "pH"       = avg_ph
  )


kable(
  rivers_avg_present,
  caption = "Average temperature, Dissolved O2, and pH per watershed",
  digits = 2,          
  format = "markdown"   
)

# mutate to total the number of times the temp goes above 25 deg

above_25 <- rivers %>%
  mutate(site = case_when(
    site %in% c("Galatin", "Gallatiin", "Gallatin") ~ "Gallatin",
    site %in% c("Madison", "Madison River") ~ "Madison",
    site %in% c("Misouri", "Missouri") ~ "Missouri",
    TRUE ~ site
  ))%>%
  group_by(site) %>%
  summarise(
    above_25 = sum(temperature >= 25, na.rm = TRUE),
    .groups = "drop"
  )

#plot

above_25_plot <- above_25%>%
  ggplot(aes(x = site, y = above_25))+
  geom_col(color = "black", fill = "red")+
  labs(title = "bar chart analysis of the number of days each watershed averaged above 25 deg (c)",
       x = "Location", 
       y = "Total number of days wter temp was above 25 (deg C)")
above_25_plot
```
```{r}
# define date format and create a numeric date column
rivers <- rivers %>%
  mutate(date = parse_date_time(date, orders = c("mdy", "ymd", "dmy")),
         month = month(date)
         )
 rivers_joined <- rivers %>%
  left_join(wqs, by = c("site", "month"))
 
 # total exeeded temps
 
 temp_exceed <- rivers_joined%>%
  group_by(site) %>%
  summarise(
    above_wqs = sum(temperature >= standard, na.rm = TRUE),
    .groups = "drop"
  )
 
 
 #plot
 wqs_plot <- temp_exceed%>%
   ggplot(aes(x = site, y = above_wqs))+
   geom_col(color = "black", fill = "green")+
   labs(title = "Number of Days Each Watershed Exceeded the Monthly WQS",
        x = "Watershed",
        y = "Number of Days")
wqs_plot
```


##Results


##Code
